using System.Windows;
using System.Windows.Controls;

namespace ApexAstro.Wpf
{
    /// <summary>
    /// Dialog window for configuring general application options and preferences.
    /// This is a modal dialog that allows users to change settings like column visibility and theme.
    /// 
    /// Key WPF Dialog Concepts:
    /// - Inherits from Window but used as a dialog (modal popup)
    /// - Uses DialogResult to indicate OK/Cancel outcome
    /// - Owner property makes it appear on top of parent window
    /// - ShowDialog() makes it modal (blocks interaction with parent)
    /// </summary>
    public partial class GeneralOptionsDialog : Window
    {
        /// <summary>
        /// Property to track whether the file size column should be shown in the main ListView.
        /// This is a simple auto-property that stores the user's preference.
        /// The dialog reads this value on creation and updates it based on user input.
        /// </summary>
        public bool ShowSizeColumn { get; set; }

        /// <summary>
        /// Property to track whether to show full filename in the File column.
        /// </summary>
        public bool ShowFullFilename { get; set; }

        /// <summary>
        /// Property to track whether the filename date column should be shown.
        /// </summary>
        public bool ShowFilenameDateColumn { get; set; }

        /// <summary>
        /// Property to track whether the filename time column should be shown.
        /// </summary>
        public bool ShowFilenameTimeColumn { get; set; }

        /// <summary>
        /// Property to track whether the filename sequence column should be shown.
        /// </summary>
        public bool ShowFilenameFrameColumn { get; set; }
        
        /// <summary>
        /// Property to track whether the median column should be shown in the main ListView.
        /// </summary>
        public bool ShowMedianColumn { get; set; }
        
        /// <summary>
        /// Property to track the median display mode (Normalized or 16-bit).
        /// </summary>
        public MedianDisplayMode MedianDisplayMode { get; set; }
        
        /// <summary>
        /// Property to track whether to show the histogram panel.
        /// </summary>
        public bool ShowHistogram { get; set; }
        
        /// <summary>
        /// Property to track whether to scan XISF files for FITS keywords.
        /// </summary>
        public bool ScanXisfForFitsKeywords { get; set; }

        /// <summary>
        /// Property to track the selected theme mode (Auto, Light, or Dark).
        /// </summary>
        public ThemeMode SelectedTheme { get; set; }

        /// <summary>
        /// Property to track whether to show the full screen help dialog.
        /// </summary>
        public bool ShowFullScreenHelp { get; set; }

        /// <summary>
        /// Property to track the pause interval between images during play mode.
        /// Value is in seconds (e.g., 0.25, 0.5, 1.0, 1.5, 2.0, 4.0, 8.0).
        /// </summary>
        public double PlayPauseInterval { get; set; }

        /// <summary>
        /// Event raised when user clicks the FITS Keywords button.
        /// </summary>
        public event Action? FitsKeywordsRequested;

        /// <summary>
        /// Event raised when user clicks the Custom Keywords button.
        /// </summary>
        public event Action? CustomKeywordsRequested;

        /// <summary>
        /// Event raised when user clicks the CSV Keywords button.
        /// </summary>
        public event Action? CsvKeywordsRequested;

        /// <summary>
        /// Default constructor - creates the dialog with default settings.
        /// This constructor is required for XAML support and is called by other constructors.
        /// 
        /// The "partial" keyword means this class is split between this .cs file and
        /// the auto-generated code from GeneralOptionsDialog.xaml.
        /// </summary>
        public GeneralOptionsDialog()
        {
            // Initialize all the UI components defined in the XAML file
            // This method is auto-generated by WPF from the XAML markup
            InitializeComponent();
        }

        /// <summary>
        /// Constructor that initializes the dialog with current settings.
        /// This is typically used when the dialog is opened from the main application
        /// to show the current setting state.
        /// 
        /// The ": this()" syntax is called constructor chaining - it means "first call 
        /// the default constructor, then execute this constructor's code."
        /// This ensures InitializeComponent() is always called first.
        /// </summary>
        /// <param name="showSizeColumn">Current value of the ShowSizeColumn setting</param>
        /// <param name="showMedianColumn">Current value of the ShowMedianColumn setting</param>
        /// <param name="theme">Current theme mode setting</param>
        /// <param name="showFullScreenHelp">Current value of the ShowFullScreenHelp setting</param>
        /// <param name="playPauseInterval">Current pause interval for play mode in seconds</param>
        /// <param name="scanXisfForFitsKeywords">Current value of the ScanXisfForFitsKeywords setting</param>
        /// <param name="medianDisplayMode">Current median display mode setting</param>
        /// <param name="showHistogram">Current value of the ShowHistogram setting</param>
        public GeneralOptionsDialog(bool showSizeColumn, bool showFullFilename, bool showFilenameDateColumn, bool showFilenameTimeColumn, bool showFilenameFrameColumn, bool showMedianColumn, ThemeMode theme, bool showFullScreenHelp, double playPauseInterval, bool scanXisfForFitsKeywords, MedianDisplayMode medianDisplayMode, bool showHistogram) : this()
        {
            // Store the initial values in our properties
            ShowSizeColumn = showSizeColumn;
            ShowFullFilename = showFullFilename;
            ShowFilenameDateColumn = showFilenameDateColumn;
            ShowFilenameTimeColumn = showFilenameTimeColumn;
            ShowFilenameFrameColumn = showFilenameFrameColumn;
            ShowMedianColumn = showMedianColumn;
            SelectedTheme = theme;
            ShowFullScreenHelp = showFullScreenHelp;
            PlayPauseInterval = playPauseInterval;
            ScanXisfForFitsKeywords = scanXisfForFitsKeywords;
            MedianDisplayMode = medianDisplayMode;
            ShowHistogram = showHistogram;
            
            // Set the checkbox state to match the current setting
            // ShowSizeColumnCheckBox is a UI control defined in the XAML file
            ShowFullFilenameCheckBox.IsChecked = showFullFilename;
            ShowFilenameDateColumnCheckBox.IsChecked = showFilenameDateColumn;
            ShowFilenameTimeColumnCheckBox.IsChecked = showFilenameTimeColumn;
            ShowFilenameFrameColumnCheckBox.IsChecked = ShowFilenameFrameColumn;
            ShowSizeColumnCheckBox.IsChecked = showSizeColumn;
            ShowMedianColumnCheckBox.IsChecked = showMedianColumn;
            ScanXisfForFitsKeywordsCheckBox.IsChecked = scanXisfForFitsKeywords;
            ShowHistogramCheckBox.IsChecked = showHistogram;
            
            // Set the median display mode radio buttons
            if (medianDisplayMode == MedianDisplayMode.Normalized)
            {
                MedianNormalizedRadioButton.IsChecked = true;
            }
            else
            {
                Median16BitRadioButton.IsChecked = true;
            }
            
            // Enable/disable median format panel based on checkbox state
            MedianFormatPanel.IsEnabled = showMedianColumn;
            
            // Set the theme combo box selection
            ThemeComboBox.SelectedIndex = (int)theme;
            
            // Set the full screen help checkbox
            ShowFullScreenHelpCheckBox.IsChecked = showFullScreenHelp;
            
            // Set the play pause interval combo box
            SelectPlayPauseInterval(playPauseInterval);
        }

        /// <summary>
        /// Helper method to select the correct combo box item based on the interval value.
        /// </summary>
        /// <param name="interval">The interval value in seconds</param>
        private void SelectPlayPauseInterval(double interval)
        {
            // Find and select the matching combo box item
            for (int i = 0; i < PlayPauseIntervalComboBox.Items.Count; i++)
            {
                if (PlayPauseIntervalComboBox.Items[i] is ComboBoxItem item)
                {
                    if (item.Tag != null && double.TryParse(item.Tag.ToString(), out double tagValue))
                    {
                        if (Math.Abs(tagValue - interval) < 0.01) // Use small epsilon for double comparison
                        {
                            PlayPauseIntervalComboBox.SelectedIndex = i;
                            return;
                        }
                    }
                }
            }
            
            // Default to 0.5 second if no match found
            PlayPauseIntervalComboBox.SelectedIndex = 1; // 0.5 second is at index 1
        }

        /// <summary>
        /// Event handler for the FITS Keywords button click.
        /// </summary>
        private void FitsKeywordsButton_Click(object sender, RoutedEventArgs e)
        {
            FitsKeywordsRequested?.Invoke();
        }

        /// <summary>
        /// Event handler for the Custom Keywords button click.
        /// </summary>
        private void CustomKeywordsButton_Click(object sender, RoutedEventArgs e)
        {
            CustomKeywordsRequested?.Invoke();
        }

        /// <summary>
        /// Event handler for the CSV Keywords button click.
        /// </summary>
        private void CsvKeywordsButton_Click(object sender, RoutedEventArgs e)
        {
            CsvKeywordsRequested?.Invoke();
        }

        /// <summary>
        /// Event handler for the OK button click.
        /// This method is called when the user clicks the OK button to accept their changes.
        /// 
        /// WPF Event Handler Pattern:
        /// - sender: The UI element that triggered the event (the OK button)
        /// - e: Event arguments containing additional information about the event
        /// - Method names typically follow the pattern: ElementName_EventName
        /// </summary>
        /// <param name="sender">The button that was clicked</param>
        /// <param name="e">Event arguments for the click event</param>
        private void Ok_Click(object sender, RoutedEventArgs e)
        {
            // Read the current checkbox state and store it in our property
            // The ?? operator means "if left side is null, use right side"
            // IsChecked is nullable bool (bool?) so it can be true, false, or null
            ShowSizeColumn = ShowSizeColumnCheckBox.IsChecked ?? false;
            ShowFullFilename = ShowFullFilenameCheckBox.IsChecked ?? true;
            ShowFilenameDateColumn = ShowFilenameDateColumnCheckBox.IsChecked ?? false;
            ShowFilenameTimeColumn = ShowFilenameTimeColumnCheckBox.IsChecked ?? false;
            ShowFilenameFrameColumn = ShowFilenameFrameColumnCheckBox.IsChecked ?? false;
            ShowMedianColumn = ShowMedianColumnCheckBox.IsChecked ?? false;
            ScanXisfForFitsKeywords = ScanXisfForFitsKeywordsCheckBox.IsChecked ?? false;
            ShowHistogram = ShowHistogramCheckBox.IsChecked ?? false;
            
            // Read the median display mode from radio buttons
            MedianDisplayMode = (MedianNormalizedRadioButton.IsChecked ?? true) 
                ? MedianDisplayMode.Normalized 
                : MedianDisplayMode.SixteenBit;
            
            // Read the selected theme from the combo box
            SelectedTheme = (ThemeMode)(ThemeComboBox.SelectedIndex);
            
            // Read the full screen help checkbox
            ShowFullScreenHelp = ShowFullScreenHelpCheckBox.IsChecked ?? true;
            
            // Read the play pause interval from combo box
            if (PlayPauseIntervalComboBox.SelectedItem is ComboBoxItem selectedItem && 
                selectedItem.Tag != null &&
                double.TryParse(selectedItem.Tag.ToString(), out double interval))
            {
                PlayPauseInterval = interval;
            }
            else
            {
                PlayPauseInterval = 0.5; // Default to 0.5 second if parsing fails
            }
            
            // Set DialogResult to true to indicate user clicked OK
            // This is how modal dialogs communicate their outcome to the caller
            DialogResult = true;
            
            // Close the dialog window
            // The calling code can check DialogResult to see if user clicked OK or Cancel
            Close();
        }

        /// <summary>
        /// Event handler for the Cancel button click.
        /// This method is called when the user clicks Cancel to discard their changes.
        /// 
        /// Cancel Pattern in Dialogs:
        /// - Set DialogResult to false to indicate user cancelled
        /// - Don't update any properties - leave them as they were
        /// - Close the dialog immediately
        /// </summary>
        /// <param name="sender">The button that was clicked (Cancel button)</param>
        /// <param name="e">Event arguments for the click event</param>
        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            // Set DialogResult to false to indicate user cancelled
            // The calling code can check this to know whether to apply changes
            DialogResult = false;
            
            // Close the dialog window without saving any changes
            Close();
        }
        
        /// <summary>
        /// Event handler for ShowMedianColumnCheckBox checked/unchecked events.
        /// Enables or disables the median format radio buttons based on checkbox state.
        /// </summary>
        private void ShowMedianColumnCheckBox_CheckedChanged(object sender, RoutedEventArgs e)
        {
            // Enable the format panel only when the checkbox is checked
            MedianFormatPanel.IsEnabled = ShowMedianColumnCheckBox.IsChecked ?? false;
        }
    } // End of GeneralOptionsDialog class
} // End of ApexAstro.Wpf namespace