using System.Windows;

namespace AstroImages.Wpf
{
    /// <summary>
    /// Splash Screen Window - displays application info and welcome message on startup.
    /// Inherits from Window which provides basic window functionality (title bar, close button, etc.).
    /// The "partial" keyword means this class works with SplashWindow.xaml to define the UI.
    /// </summary>
    public partial class SplashWindow : Window
    {
        private readonly AppConfig? _appConfig;

        /// <summary>
        /// Property to track if user checked "Don't show this again".
        /// Public get (anyone can read) but private set (only this class can change it).
        /// This is called an "auto-property" - C# automatically creates the backing field.
        /// </summary>
        public bool DontShowAgain { get; private set; }

        /// <summary>
        /// Constructor - called when creating a new SplashWindow instance.
        /// This runs before the window is displayed.
        /// </summary>
        /// <param name="showSplashScreen">Current value of ShowSplashScreen setting - if false, checkbox will be checked</param>
        /// <param name="appConfig">Optional app configuration for update checking</param>
        public SplashWindow(bool showSplashScreen = true, AppConfig? appConfig = null)
        {
            // InitializeComponent() is generated by WPF - it loads the XAML layout
            // and connects event handlers. Always call this first in WPF constructors.
            InitializeComponent();
            
            _appConfig = appConfig;
            
            // Set the current year for the copyright notice
            CopyrightYear.Text = DateTime.Now.Year.ToString();
            
            // Set the version dynamically from assembly information
            var version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version;
            if (version != null)
            {
                VersionTextBlock.Text = $"Version {version.Major}.{version.Minor}.{version.Build}";
            }
            
            // Initialize checkbox based on current setting
            // If ShowSplashScreen is false, that means "don't show again" was previously checked
            DontShowAgainCheckBox.IsChecked = !showSplashScreen;
        }

        /// <summary>
        /// Event handler for the OK button click.
        /// In WPF, event handlers follow the pattern: (object sender, EventArgs e)
        /// sender = the control that triggered the event (the OK button)
        /// e = additional information about the event
        /// </summary>
        /// <param name="sender">The button that was clicked</param>
        /// <param name="e">Event arguments with details about the click</param>
        private void OkButton_Click(object sender, RoutedEventArgs e)
        {
            // Get the checkbox state - IsChecked can be true, false, or null (for indeterminate)
            // The ?? operator means "if left side is null, use right side"
            // So if IsChecked is null, we treat it as false
            DontShowAgain = DontShowAgainCheckBox.IsChecked ?? false;
            
            // Set DialogResult to true - this tells the calling code that user clicked OK
            // When ShowDialog() is used, it returns this DialogResult value
            this.DialogResult = true;
            
            // Close the window - this will return control to the calling code
            this.Close();
        }

        /// <summary>
        /// Event handler for Check for Updates button
        /// </summary>
        private async void CheckUpdatesButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                this.Cursor = System.Windows.Input.Cursors.Wait;
                
                var repoOwner = _appConfig?.UpdateRepoOwner ?? "kfaubel";
                var repoName = _appConfig?.UpdateRepoName ?? "AstroImages";
                
                using var updateService = new Services.UpdateService(repoOwner, repoName);
                var updateInfo = await updateService.CheckForUpdatesAsync();
                
                this.Cursor = System.Windows.Input.Cursors.Arrow;
                
                if (updateInfo != null)
                {
                    var updateDialog = new UpdateDialog(updateInfo, updateService);
                    updateDialog.Owner = this;
                    updateDialog.ShowDialog();
                }
                else
                {
                    System.Windows.MessageBox.Show(
                        "You are running the latest version.",
                        "No Updates Available",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                this.Cursor = System.Windows.Input.Cursors.Arrow;
                System.Windows.MessageBox.Show(
                    $"Error checking for updates: {ex.Message}",
                    "Update Check Failed",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// Event handler for View Log button
        /// </summary>
        private void ViewLogButton_Click(object sender, RoutedEventArgs e)
        {
            // Get the logging service from App
            var loggingService = App.LoggingService;
            if (loggingService != null)
            {
                var logWindow = new LogViewerWindow(loggingService);
                logWindow.Owner = this;
                logWindow.ShowDialog();
            }
            else
            {
                System.Windows.MessageBox.Show(
                    "Logging service is not available.",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
        }

        /// <summary>
        /// Event handler for Documentation button
        /// </summary>
        private void DocumentationButton_Click(object sender, RoutedEventArgs e)
        {
            var documentationWindow = new DocumentationWindow();
            documentationWindow.Owner = this;
            documentationWindow.ShowDialog();
        }

        /// <summary>
        /// Event handler for Feedback button
        /// </summary>
        private void FeedbackButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var url = "https://github.com/kfaubel/AstroImages/issues";
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = url,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show(
                    $"Unable to open browser: {ex.Message}\\n\\nPlease visit:\\nhttps://github.com/kfaubel/AstroImages/issues",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }
    }
}